CREATE TABLE PERSON(
	EMP_NO CHAR(10) PRIMARY KEY,
	EMP_NAME VARCHAR(30) NOT NULL,
	JOB_TITLE VARCHAR(20) DEFAULT '사원' NOT NULL,
	DEPT_NAME VARCHAR(20),
	SALARY NUMBER(10) DEFAULT 0,
	HIRE_DATE DATE DEFAULT TRUNC(SYSDATE)
);

DROP TABLE PERSON;

DELETE FROM PERSON; -- 데이터 전체 삭제


SELECT * FROM PERSON; -- 전체조회
SELECT * FROM PERSON ORDER BY EMP_NAME ASC; -- 오름차순 조회
SELECT * FROM PERSON ORDER BY EMP_NAME DESC; -- 이름 내림차순
SELECT * FROM PERSON WHERE JOB_TITLE = '팀장'; -- 팀장만 조회
SELECT * FROM PERSON WHERE DEPT_NAME = '영업부';
SELECT * FROM PERSON WHERE SALARY > 50000000; -- 연봉 5000만 이상

INSERT INTO PERSON VALUES('A20240042', '이형준', '사원', '개발부', 50000000, SYSDATE);

