# 관리자 계정으로 진행 -root

# DB 생성
CREATE DATABASE SCOTT DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

# 생성한 데이터베이스 목록 확인
SHOW DATABASES;
DROP DATABASES SCOTT; -- DB삭제

# DB문자코드 변경
# ALTER DATABASE DATABASES명 DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;
ALTER DATABASE SCOTT DEFAULT CHARACTER SET UTF8MB4 COLLATE UTF8MB4_GENERAL_CI;

# 계정생성
CREATE USER 'SCOTT'@'%' IDENTIFIED BY '123456'; -- %에는 원래 HOST주소입력 %는 상관없이 접속 하겠다는 의미

# 뭐든 권한 부여 PRIVILEGES
GRANT ALL PRIVILEGES ON SCOTT.* TO 'SCOTT'@'%'; # 왼쪽에 있는 권한을 오른쪽 TO에 주겟다 (SCOTT.* : DB)

# 권한 회수 방법
REVOKE ALL PRIVILEGES ON SCOTT.* FROM 'SCOTT'@'%';

# DB선택 : mariadb는 DB를 먼저 선택해주어야 테이블 생성이 가능하다.
USE SCOTT; # 만약 DB선택이 번거롭다면 처음 연결할때 DataBase에 DB명을 입력하여 연결하여 만들면된다.

CREATE TABLE STUDENT(
    STD_NO CHAR(8) PRIMARY KEY,
    STD_NAME VARCHAR(30),
    MAJOR_NO DECIMAL(2) DEFAULT 0,
    STD_SCORE FLOAT(3,2)
);

INSERT INTO STUDENT VALUES('20201111','홍길동',3,2.4);
INSERT INTO STUDENT VALUES('20202222','김철수',1,3.4);
INSERT INTO STUDENT VALUES('20203333','황보원',4,4.4);
INSERT INTO STUDENT VALUES('20204444','이인수',5,1.5);
INSERT INTO STUDENT VALUES('20205555','박철수',2,3.6);

SELECT * FROM STUDENT;