CREATE TABLE TAB1(
	SAL NUMBER
);

INSERT INTO TAB1(SAL) VALUES(3000);
INSERT INTO TAB1(SAL) VALUES(3500);
INSERT INTO TAB1(SAL) VALUES(4000);
INSERT INTO TAB1(SAL) VALUES(4200);
INSERT INTO TAB1(SAL) VALUES(6000);

SELECT * FROM TAB1;

SELECT SUM(DECODE(SIGN(SAL-4000),1,1,0)) FROM TAB1;

DROP TABLE TAB1;

CREATE TABLE TAB1(
	COL1 NUMBER,
	COL2 CHAR(1)
);
INSERT INTO TAB1(COL1,COL2) VALUES(1,'A');
INSERT INTO TAB1(COL1) VALUES(2);
INSERT INTO TAB1(COL1,COL2) VALUES(3,'B');
INSERT INTO TAB1(COL1,COL2) VALUES(4,'C');
SELECT * FROM TAB1;

CREATE TABLE TAB2(
	COL1 NUMBER,
	COL2 CHAR(1)
);
INSERT INTO TAB2(COL1,COL2) VALUES(1,'A');
INSERT INTO TAB2(COL1) VALUES(2);
INSERT INTO TAB2(COL1,COL2) VALUES(3,'B');

SELECT SUM(A.COL1) FROM TAB1 A, TAB2 B WHERE A.COL2 <> B.COL2;
