CREATE TABLE TAB1(
	SAL NUMBER
);

INSERT INTO TAB1(SAL) VALUES(3000);
INSERT INTO TAB1(SAL) VALUES(3500);
INSERT INTO TAB1(SAL) VALUES(4000);
INSERT INTO TAB1(SAL) VALUES(4200);
INSERT INTO TAB1(SAL) VALUES(6000);

SELECT * FROM TAB1;

SELECT SUM(DECODE(SIGN(SAL-4000),1,1,0)) FROM TAB1;

DROP TABLE TAB1;

CREATE TABLE TAB1(
	COL1 NUMBER,
	COL2 CHAR(1)
);
INSERT INTO TAB1(COL1,COL2) VALUES(1,'A');
INSERT INTO TAB1(COL1) VALUES(2);
INSERT INTO TAB1(COL1,COL2) VALUES(3,'B');
INSERT INTO TAB1(COL1,COL2) VALUES(4,'C');
SELECT * FROM TAB1;

CREATE TABLE TAB2(
	COL1 NUMBER,
	COL2 CHAR(1)
);
INSERT INTO TAB2(COL1,COL2) VALUES(1,'A');
INSERT INTO TAB2(COL1) VALUES(2);
INSERT INTO TAB2(COL1,COL2) VALUES(3,'B');

SELECT SUM(A.COL1) FROM TAB1 A, TAB2 B WHERE A.COL2 <> B.COL2;

SELECT TO_CHAR(TO_DATE('2023.01.10 10', 'YYYY.MM.DD HH24') + 1/24/(60/10), 'YYYY.MM.DD HH24:MI:SS') FROM DUAL;

CREATE TABLE 서비스(
	서비스번호 VARCHAR2(10) PRIMARY KEY,
	서비스명 VARCHAR2(100) NULL,
	개시일자 DATE NOT NULL
);
INSERT INTO 서비스 VALUES('999','','2015-11-11');

SELECT * FROM 서비스 WHERE 서비스번호 = 1;

CREATE TABLE TABLE_A(
	TABKEY NUMBER,
	COLA NUMBER,
	COLB VARCHAR2(10),
	COLC NUMBER
);

INSERT INTO TABLE_A VALUES(1,NULL,'가',NULL);
INSERT INTO TABLE_A VALUES(2,1,'가',5);
INSERT INTO TABLE_A VALUES(3,NULL,'나',2);
INSERT INTO TABLE_A VALUES(4,3,'나',0);
INSERT INTO TABLE_A VALUES(5,NULL,NULL,3);
INSERT INTO TABLE_A VALUES(6,5,'다',0);
INSERT INTO TABLE_A VALUES(7,NULL,'다',NULL);

SELECT COLB
	,MAX(COLA) AS COLA1
	,MIN(COLA) AS COLA2
	,SUM(COLA + COLC) AS SUMAC
FROM TABLE_A
GROUP BY COLB;


SELECT TO_CHAR(TO_DATE('2019.02.25', 'YYYY.MM.DD') +
1/24/60, 'YYYY.MM.DD HH24:MI:SS') FROM DUAL;