CREATE TABLE BOARD_MEMBER (
	MEMBER_ID VARCHAR2(50) NOT NULL,
MEMBER_PW CHAR(128) NOT NULL,
MEMBER_NAME VARCHAR2(50) NOT NULL,
NICKNAME VARCHAR2(50) NOT NULL
);

CREATE TABLE BOARD(
	B_NO NUMBER NOT NULL,
MEMBER_ID VARCHAR2(50) NOT NULL,
B_TITLE VARCHAR2(150) NOT NULL,
B_CONTENT CLOB NOT NULL,
B_CREATEDATE DATE DEFAULT SYSDATE NOT NULL,
B_UPDATEDATE DATE DEFAULT SYSDATE NOT NULL,
B_VIEWS NUMBER DEFAULT 0 NULL
);

CREATE TABLE LIKES_BOARD (
	MEMBER_ID VARCHAR2(50) NOT NULL,
B_NO NUMBER NOT NULL,
LIKED NUMBER NULL
);

CREATE TABLE COMMENT (
	C_NO NUMBER NOT NULL,
B_NO NUMBER NOT NULL,
MEMBER_ID VARCHAR2(50) NOT NULL,
C_CONTENT VARCHAR2(1000) NOT NULL,
C_CREATEDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE DISLIKES_BOARD (
	MEMBER_ID VARCHAR2(50) NOT NULL,
B_NO NUMBER NOT NULL,
DISLIKED NUMBER NULL
);

CREATE TABLE BOARD_FILE (
	F_NO CHAR(10) NOT NULL,
B_NO NUMBER NOT NULL,
F_PATH VARCHAR2(256) NULL
);

CREATE TABLE DISLIKES_COMMENT (
	C_NO NUMBER NOT NULL,
ID VARCHAR2(50) NOT NULL
);

CREATE TABLE LIKES_COMMENT (
	C_NO NUMBER NOT NULL,
ID VARCHAR2(50) NOT NULL
);

ALTER TABLE BOARD_MEMBER ADD CONSTRAINT PK_BOARD_MEMBER PRIMARY KEY (MEMBER_ID);

ALTER TABLE BOARD ADD CONSTRAINT PK_BOARD PRIMARY KEY (
	B_NO,
MEMBER_ID
);

ALTER TABLE LIKES_BOARD ADD CONSTRAINT PK_LIKES_BOARD PRIMARY KEY (
	MEMBER_ID,
B_NO
);

ALTER TABLE COMMENT ADD CONSTRAINT PK_COMMENT PRIMARY KEY (
	C_NO,
B_NO,
MEMBER_ID
);

ALTER TABLE DISLIKES_BOARD ADD CONSTRAINT PK_DISLIKES_BOARD PRIMARY KEY (
	MEMBER_ID,
B_NO
);

ALTER TABLE BOARD_FILE ADD CONSTRAINT PK_BOARD_FILE PRIMARY KEY (
	F_NO,
B_NO
);

ALTER TABLE DISLIKES_COMMENT ADD CONSTRAINT PK_DISLIKES_COMMENT PRIMARY KEY (
	C_NO,
ID
);

ALTER TABLE LIKES_COMMENT ADD CONSTRAINT PK_LIKES_COMMENT PRIMARY KEY (
	C_NO,
ID
);

ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER_TO_BOARD_1 FOREIGN KEY (MEMBER_ID)
REFERENCES BOARD_MEMBER (MEMBER_ID);

ALTER TABLE LIKES_BOARD ADD CONSTRAINT FK_BOARD_MEMBER_TO_LIKES_BOARD_1 FOREIGN KEY (MEMBER_ID)
REFERENCES BOARD_MEMBER (MEMBER_ID);

ALTER TABLE LIKES_BOARD ADD CONSTRAINT FK_BOARD_TO_LIKES_BOARD_1 FOREIGN KEY (B_NO)
REFERENCES BOARD (B_NO);

ALTER TABLE COMMENT ADD CONSTRAINT FK_BOARD_TO_COMMENT_1 FOREIGN KEY (B_NO)
REFERENCES BOARD (B_NO);

ALTER TABLE COMMENT ADD CONSTRAINT FK_BOARD_MEMBER_TO_COMMENT_1 FOREIGN KEY (MEMBER_ID)
REFERENCES BOARD_MEMBER (MEMBER_ID);

ALTER TABLE DISLIKES_BOARD ADD CONSTRAINT FK_BOARD_MEMBER_TO_DISLIKES_BOARD_1 FOREIGN KEY (MEMBER_ID)
REFERENCES BOARD_MEMBER (MEMBER_ID);

ALTER TABLE DISLIKES_BOARD ADD CONSTRAINT FK_BOARD_TO_DISLIKES_BOARD_1 FOREIGN KEY (B_NO)
REFERENCES BOARD (B_NO);

ALTER TABLE BOARD_FILE ADD CONSTRAINT FK_BOARD_TO_BOARD_FILE_1 FOREIGN KEY (B_NO)
REFERENCES BOARD (B_NO);

ALTER TABLE DISLIKES_COMMENT ADD CONSTRAINT FK_COMMENT_TO_DISLIKES_COMMENT_1 FOREIGN KEY (C_NO)
REFERENCES COMMENT (C_NO);

ALTER TABLE DISLIKES_COMMENT ADD CONSTRAINT FK_BOARD_MEMBER_TO_DISLIKES_COMMENT_1 FOREIGN KEY (ID)
REFERENCES BOARD_MEMBER (MEMBER_ID);

ALTER TABLE LIKES_COMMENT ADD CONSTRAINT FK_COMMENT_TO_LIKES_COMMENT_1 FOREIGN KEY (C_NO)
REFERENCES COMMENT (C_NO);

ALTER TABLE LIKES_COMMENT ADD CONSTRAINT FK_BOARD_MEMBER_TO_LIKES_COMMENT_1 FOREIGN KEY (ID)
REFERENCES BOARD_MEMBER (MEMBER_ID);
